version: '3.7'
services:

  database-server:
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      DB_NAME: $DB_NAME
      DB_USERNAME: $DB_USERNAME
      DB_PASSWD: $DB_PASSWD
      GLOBAL_ADMIN_PASS_HASH: $GLOBAL_ADMIN_PASS_HASH
    build:
      context: ./database-server
      dockerfile: Dockerfile
    image: database-server
    hostname: database-server
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: "udp://${GRAYLOG_HOST}:${GRAYLOG_GELF_PORT}"
        tag: "schedulerdb"
    volumes:
      - ${DB_VOLUME_PATH}:/var/lib/postgresql/data
    ports:
      - 5432:5432

  auth-server:
    environment:
      PROFILE: $PROFILE
      KEY_STORE_FILE: $KEY_STORE_FILE
      KEY_STORE_PASSWORD: $KEY_STORE_PASSWORD
      KEY_ALIAS: $KEY_ALIAS
      JWK_KID: $JWK_KID
      VALIDITY_SECONDS: $VALIDITY_SECONDS
      GRAYLOG_HOST: $GRAYLOG_HOST
      GRAYLOG_GELF_PORT: $GRAYLOG_GELF_PORT
      JWT_SET_URI: $JWT_SET_URI
      DB_DRIVER_CLASS_NAME: $DB_DRIVER_CLASS_NAME
      DB_URL: $DB_URL
      DB_NAME: $DB_NAME
      DB_USERNAME: $DB_USERNAME
      DB_PASSWD: $DB_PASSWD
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    image: auth-server
    hostname: auth-server
    restart: always
    volumes:
      - ${LOG_VOLUME_PATH}:/logs
    ports:
      - 5000:5000

  work-schedule-service:
    environment:
      PROFILE: $PROFILE
      GRAYLOG_HOST: $GRAYLOG_HOST
      GRAYLOG_GELF_PORT: $GRAYLOG_GELF_PORT
      JWT_SET_URI: $JWT_SET_URI
      DB_DRIVER_CLASS_NAME: $DB_DRIVER_CLASS_NAME
      DB_URL: $DB_URL
      DB_NAME: $DB_NAME
      DB_USERNAME: $DB_USERNAME
      DB_PASSWD: $DB_PASSWD
    build:
      context: ./work-schedule-service
      dockerfile: Dockerfile
    image: work-schedule-service
    hostname: work-schedule-service
    restart: always
    volumes:
      - ${LOG_VOLUME_PATH}:/logs
    depends_on:
      - auth-server
    ports:
      - 8080:8080

  frontend-server:
    build:
      context: ./frontend-server
      dockerfile: Dockerfile
    image: frontend-server
    hostname: frontend-server
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: "udp://${GRAYLOG_HOST}:${GRAYLOG_GELF_PORT}"
        tag: "nginx"
    volumes:
      - ${FRONTEND_VOLUME_PATH}:/usr/share/nginx/html
    ports:
      - 4000:4000
      - 80:80 #50680
