spring:

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_SET_URI}

  jackson:
    date-format: "yyyy-MM-dd"

  jpa:
    open-in-view: false

server:
  port: 5000
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

security:
  jwt:
    keyStoreFile: ${KEY_STORE_FILE}
    keyStorePassword: ${KEY_STORE_PASSWORD}
    keyAlias: ${KEY_ALIAS}
    jwkKid: ${JWK_KID}
    validitySeconds: ${VALIDITY_SECONDS}
